image: quay.io/pypa/manylinux_2_24_x86_64

stages:
  - build
  - deploy

.build: &build
  stage: build
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - $PYTHON -m pip install -U pip
    - apt update
    - apt install -y tree
  script:
    - $PYTHON -m pip wheel -w wh .
    - tree
  artifacts:
    paths:
      - wh/cmeel_example*.whl

deploy:
  stage: deploy
  retry:
    max: 2
    when: runner_system_failure
  only:
    - tags
  before_script:
    - python3.10 -m pip install -U pip
    - python3.10 -m pip install -U twine
    - apt update
    - apt install -y tree
  script:
    - tree
    - python3.10 -m twine upload -u gitlab-ci-token -p ${CI_JOB_TOKEN} --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi wh/*

build-3.8:
  <<: *build
  variables:
    PYTHON: python3.8

build-3.9:
  <<: *build
  variables:
    PYTHON: python3.9

build-3.10:
  <<: *build
  variables:
    PYTHON: python3.10
