pull_request_rules:
  - name: merge automatically when CI passes and PR is approved
    conditions:
      - check-success = "Build 3.10 on macos"
      - check-success = "Build 3.10 on ubuntu"
      - check-success = "Build 3.11 on macos"
      - check-success = "Build 3.11 on ubuntu"
      - check-success = "Build 3.12 on macos"
      - check-success = "Build 3.12 on ubuntu"
      - check-success = "Build 3.13 on macos"
      - check-success = "Build 3.13 on ubuntu"
      - check-success = "Build 3.8 on macos"
      - check-success = "Build 3.8 on ubuntu"
      - check-success = "Build 3.9 on macos"
      - check-success = "Build 3.9 on ubuntu"
      - check-success = "sdist"
      - check-success = "Test 3.10 on macos"
      - check-success = "Test 3.10 on ubuntu"
      - check-success = "Test 3.11 on macos"
      - check-success = "Test 3.11 on ubuntu"
      - check-success = "Test 3.12 on macos"
      - check-success = "Test 3.12 on ubuntu"
      - check-success = "Test 3.13 on macos"
      - check-success = "Test 3.13 on ubuntu"
      - check-success = "Test 3.8 on macos"
      - check-success = "Test 3.8 on ubuntu"
      - check-success = "Test 3.9 on macos"
      - check-success = "Test 3.9 on ubuntu"
      - check-success = "Wheel cp310 macos-13 x86_64"
      - check-success = "Wheel cp310 macos-14 arm64"
      - check-success = "Wheel cp310 ubuntu-24.04-arm aarch64"
      - check-success = "Wheel cp310 ubuntu-24.04 x86_64"
      - check-success = "Wheel cp311 macos-13 x86_64"
      - check-success = "Wheel cp311 macos-14 arm64"
      - check-success = "Wheel cp311 ubuntu-24.04-arm aarch64"
      - check-success = "Wheel cp311 ubuntu-24.04 x86_64"
      - check-success = "Wheel cp312 macos-13 x86_64"
      - check-success = "Wheel cp312 macos-14 arm64"
      - check-success = "Wheel cp312 ubuntu-24.04-arm aarch64"
      - check-success = "Wheel cp312 ubuntu-24.04 x86_64"
      - check-success = "Wheel cp313 macos-13 x86_64"
      - check-success = "Wheel cp313 macos-14 arm64"
      - check-success = "Wheel cp313 ubuntu-24.04-arm aarch64"
      - check-success = "Wheel cp313 ubuntu-24.04 x86_64"
      - check-success = "Wheel cp38 macos-13 x86_64"
      - check-success = "Wheel cp38 ubuntu-24.04-arm aarch64"
      - check-success = "Wheel cp38 ubuntu-24.04 x86_64"
      - check-success = "Wheel cp39 macos-13 x86_64"
      - check-success = "Wheel cp39 macos-14 arm64"
      - check-success = "Wheel cp39 ubuntu-24.04-arm aarch64"
      - check-success = "Wheel cp39 ubuntu-24.04 x86_64"
      - check-success = "pre-commit.ci - pr"
      - or:
        - approved-reviews-by = nim65s
        - author = nim65s
        - author = dependabot[bot]
        - author = github-actions[bot]
        - author = pre-commit-ci[bot]
    actions:
      merge:
