pull_request_rules:
  - name: merge automatically when CI passes and PR is approved
    conditions:
      - check-success = "Build 3.10 on macos"
      - check-success = "Build 3.10 on ubuntu"
      - check-success = "Build 3.11 on macos"
      - check-success = "Build 3.11 on ubuntu"
      - check-success = "Build 3.12 on macos"
      - check-success = "Build 3.12 on ubuntu"
      - check-success = "Build 3.13 on macos"
      - check-success = "Build 3.13 on ubuntu"
      - check-success = "Build 3.8 on macos"
      - check-success = "Build 3.8 on ubuntu"
      - check-success = "Build 3.9 on macos"
      - check-success = "Build 3.9 on ubuntu"
      - check-success = "Wheel cp310 macos aarch64"
      - check-success = "Wheel cp310 macos x86_64"
      - check-success = "Wheel cp310 ubuntu aarch64"
      - check-success = "Wheel cp310 ubuntu x86_64"
      - check-success = "Wheel cp311 macos aarch64"
      - check-success = "Wheel cp311 macos x86_64"
      - check-success = "Wheel cp311 ubuntu aarch64"
      - check-success = "Wheel cp311 ubuntu x86_64"
      - check-success = "Wheel cp312 macos aarch64"
      - check-success = "Wheel cp312 macos x86_64"
      - check-success = "Wheel cp312 ubuntu aarch64"
      - check-success = "Wheel cp312 ubuntu x86_64"
      - check-success = "Wheel cp313 macos aarch64"
      - check-success = "Wheel cp313 ubuntu aarch64"
      - check-success = "Wheel cp313 ubuntu x86_64"
      - check-success = "Wheel cp38 macos aarch64"
      - check-success = "Wheel cp38 macos x86_64"
      - check-success = "Wheel cp38 ubuntu aarch64"
      - check-success = "Wheel cp38 ubuntu x86_64"
      - check-success = "Wheel cp39 macos aarch64"
      - check-success = "Wheel cp39 macos x86_64"
      - check-success = "Wheel cp39 ubuntu aarch64"
      - check-success = "Wheel cp39 ubuntu x86_64"
      - check-success = "sdist"
      - check-success = "pre-commit.ci - pr"
      - or:
        - approved-reviews-by = nim65s
        - author = nim65s
        - author = dependabot[bot]
        - author = github-actions[bot]
        - author = pre-commit-ci[bot]
    actions:
      merge:
