name: Release on GitHub & PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - run: python -m pip install -U pip
      - run: python -m pip install cibuildwheel
      - run: touch setup.py
      - run: python -m cibuildwheel --output-dir wh
        env:
          CIBW_ARCHS_LINUX: "auto aarch64 ppc64le s390x"
          CIBW_ARCHS_MACOS: "x86_64 universal2"
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_MANYLINUX_AARCH64_IMAGE: "quay.io/pypa/manylinux_2_28_aarch64"
          CIBW_MANYLINUX_PPC64LE_IMAGE: "quay.io/pypa/manylinux_2_28_ppc64le"
          CIBW_MANYLINUX_I686_IMAGE: "quay.io/pypa/manylinux2014_i686"
          CIBW_MANYLINUX_S390X_IMAGE: "quay.io/pypa/manylinux2014_s390x"
      - uses: actions/upload-artifact@v3
        with:
          path: wh
  release:
    needs: ["build_wheels"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v3
      - run: python -m pip install twine
      - run: python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} artifact/cmeel_example*.whl
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG}}" -n "$(awk '/## \[${{ env.TAG }}] - /{flag=1;next}/## \[/{flag=0}flag' CHANGELOG.md)" ${{ env.TAG }} wh/cmeel_example*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
