name: Release on GitHub & PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: quay.io/pypa/manylinux_2_24_x86_64
    steps:
      - uses: actions/checkout@v2
      - run: python3.8 -m pip install -U pip
      - run: python3.9 -m pip install -U pip
      - run: python3.10 -m pip install -U pip
      - run: python3.8 -m pip wheel .
      - run: python3.9 -m pip wheel .
      - run: python3.10 -m pip wheel .
      - run: python3.10 -m pip install twine
      - run: python3.10 -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} cmeel_example*.whl
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG}}" -n "$(awk '/## \[${{ env.TAG }}] - /{flag=1;next}/## \[/{flag=0}flag' CHANGELOG.md)" ${{ env.TAG }} cmeel_example*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
