name: Release on GitHub & PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_24_x86_64
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - run: python${{ matrix.python }} -m pip install -U pip
      - run: python${{ matrix.python }} -m pip wheel -w wh .
      - run: apt-get update
      - run: apt-get install -y tree
      - run: pwd
      - run: tree
      - uses: actions/upload-artifact@v3
        with:
          name: wh
          path: wh
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v3
        with:
          path: wh
      - run: sudo apt-get update
      - run: sudo apt-get install -y tree
      - run: pwd
      - run: tree
      - run: python -m pip install twine
      - run: python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} wh/cmeel_example*.whl
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG}}" -n "$(awk '/## \[${{ env.TAG }}] - /{flag=1;next}/## \[/{flag=0}flag' CHANGELOG.md)" ${{ env.TAG }} wh/cmeel_example*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
