name: Check build

on: ["push", "pull_request"]

jobs:
  test:
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        #os: ["ubuntu-latest", "macos-latest"]
        #python-version: ["3.8","3.9","3.10"]
        os: ["windows-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install .
        env:
          CMAKE_GENERATOR: Ninja
      - run: cmeel-add 3 4
      - run: python -c "import cmeel_example; assert cmeel_example.cmeel_add(3, 4) == 7"
