name: Build Wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install cibuildwheel
      - run: python -m cibuildwheel --output-dir wh
      - uses: actions/upload-artifacts@v3
        with:
          path: wh
