name: Build Wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: python3 -m pip install -U pip
      - run: python3 -m pip install -U ninja
      - run: python3 -m pip wheel -w wh .
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"
          CMAKE_GENERATOR_PLATFORM: "x64"
          CXXFLAGS: -DMS_WIN64
      #- run: python -m pip install cibuildwheel
      #- run: touch setup.py
      #- run: python -m cibuildwheel --output-dir wh
        #env:
          #CIBW_SKIP: "*-win32"
      - uses: actions/upload-artifact@v3
        with:
          path: wh
